[package]
name = "routes"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
actix-cors = "0.6.2"
actix-multiresponse = "0.2.0"
tracing = "0.1.36"
tracing-actix-web = "0.6.0"
thiserror = "1.0.32"

[dependencies.dal]
path = "../dal"

[dependencies.proto]
path = "../proto"